services:
  etl:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fmcg-inventory-etl
    working_dir: /app
    volumes:
      - .:/app
    command: python inspect_dataset.py