{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a5826c8f-efbe-4a4e-9ef2-2188c0faa89c",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Complete ETL Pipeline - Single command execution\n",
    "# This script can be run from terminal: python run_pipeline.py\n",
    "\n",
    "import sys\n",
    "import os\n",
    "import subprocess\n",
    "from pathlib import Path\n",
    "import datetime\n",
    "import logging\n",
    "\n",
    "# ============================================\n",
    "# 1. SETUP\n",
    "# ============================================\n",
    "\n",
    "# Get the project root directory\n",
    "PROJECT_ROOT = Path(__file__).parent.absolute()\n",
    "DATA_RAW = PROJECT_ROOT / 'data' / 'raw'\n",
    "DATA_PROCESSED = PROJECT_ROOT / 'data' / 'processed'\n",
    "LOGS_DIR = PROJECT_ROOT / 'logs'\n",
    "\n",
    "# Create directories if they don't exist\n",
    "DATA_RAW.mkdir(parents=True, exist_ok=True)\n",
    "DATA_PROCESSED.mkdir(parents=True, exist_ok=True)\n",
    "LOGS_DIR.mkdir(parents=True, exist_ok=True)\n",
    "\n",
    "# Setup logging\n",
    "log_file = LOGS_DIR / 'pipeline_execution.log'\n",
    "logging.basicConfig(\n",
    "    level=logging.INFO,\n",
    "    format='%(asctime)s - %(levelname)s - %(message)s',\n",
    "    handlers=[\n",
    "        logging.FileHandler(log_file, mode='w', encoding='utf-8'),\n",
    "        logging.StreamHandler(sys.stdout)\n",
    "    ]\n",
    ")\n",
    "logger = logging.getLogger(__name__)\n",
    "\n",
    "# ============================================\n",
    "# 2. CHECK ENVIRONMENT\n",
    "# ============================================\n",
    "\n",
    "def check_python_version():\n",
    "    \"\"\"Check if Python version is compatible\"\"\"\n",
    "    version = sys.version_info\n",
    "    if version.major < 3 or (version.major == 3 and version.minor < 8):\n",
    "        logger.error(f\"Python 3.8+ required. Current: {version.major}.{version.minor}\")\n",
    "        return False\n",
    "    logger.info(f\"✅ Python version: {version.major}.{version.minor}.{version.micro}\")\n",
    "    return True\n",
    "\n",
    "\n",
    "def check_requirements():\n",
    "    \"\"\"Check if all required packages are installed\"\"\"\n",
    "    required_packages = [\n",
    "        'pandas',\n",
    "        'numpy',\n",
    "        'nbformat',\n",
    "        'nbconvert'\n",
    "    ]\n",
    "    \n",
    "    missing = []\n",
    "    for package in required_packages:\n",
    "        try:\n",
    "            __import__(package)\n",
    "            logger.info(f\"✅ {package} found\")\n",
    "        except ImportError:\n",
    "            missing.append(package)\n",
    "            logger.warning(f\"❌ {package} missing\")\n",
    "    \n",
    "    if missing:\n",
    "        logger.error(f\"Missing packages: {', '.join(missing)}\")\n",
    "        logger.info(\"Run: pip install -r requirements.txt\")\n",
    "        return False\n",
    "    \n",
    "    return True\n",
    "\n",
    "\n",
    "def check_raw_files():\n",
    "    \"\"\"Check if all required raw files exist\"\"\"\n",
    "    required_files = [\n",
    "        'sales.csv',\n",
    "        'orders.csv',\n",
    "        'inventory.csv',\n",
    "        'warehouses.csv'\n",
    "    ]\n",
    "    \n",
    "    missing = []\n",
    "    for filename in required_files:\n",
    "        filepath = DATA_RAW / filename\n",
    "        if filepath.exists():\n",
    "            logger.info(f\"✅ {filename} found ({filepath.stat().st_size} bytes)\")\n",
    "        else:\n",
    "            missing.append(filename)\n",
    "            logger.warning(f\"❌ {filename} missing\")\n",
    "    \n",
    "    if missing:\n",
    "        logger.error(f\"Missing raw files: {', '.join(missing)}\")\n",
    "        logger.info(f\"Please place files in: {DATA_RAW}\")\n",
    "        return False\n",
    "    \n",
    "    return True\n",
    "\n",
    "\n",
    "def check_notebooks():\n",
    "    \"\"\"Check if all required notebook files exist\"\"\"\n",
    "    required_notebooks = [\n",
    "        'extract.ipynb',\n",
    "        'transform.ipynb',\n",
    "        'validate.ipynb',\n",
    "        'integrate.ipynb',\n",
    "        'analytics.ipynb'\n",
    "    ]\n",
    "    \n",
    "    src_dir = PROJECT_ROOT / 'src'\n",
    "    \n",
    "    missing = []\n",
    "    for nb in required_notebooks:\n",
    "        nb_path = src_dir / nb\n",
    "        if nb_path.exists():\n",
    "            logger.info(f\"✅ {nb} found\")\n",
    "        else:\n",
    "            missing.append(nb)\n",
    "            logger.warning(f\"❌ {nb} missing\")\n",
    "    \n",
    "    if missing:\n",
    "        logger.error(f\"Missing notebooks: {', '.join(missing)}\")\n",
    "        return False\n",
    "    \n",
    "    return True\n",
    "\n",
    "\n",
    "# ============================================\n",
    "# 3. RUN THE PIPELINE\n",
    "# ============================================\n",
    "\n",
    "def run_notebook_as_script(notebook_path):\n",
    "    \"\"\"\n",
    "    Run a Jupyter notebook as a Python script using nbconvert\n",
    "    \"\"\"\n",
    "    try:\n",
    "        # Convert notebook to Python script\n",
    "        script_path = notebook_path.with_suffix('.py')\n",
    "        cmd = [\n",
    "            'jupyter', 'nbconvert',\n",
    "            '--to', 'script',\n",
    "            '--output', script_path.stem,\n",
    "            str(notebook_path)\n",
    "        ]\n",
    "        subprocess.check_call(cmd, cwd=notebook_path.parent)\n",
    "        \n",
    "        # Run the Python script\n",
    "        cmd = [sys.executable, str(script_path)]\n",
    "        result = subprocess.check_call(cmd, cwd=notebook_path.parent)\n",
    "        \n",
    "        # Clean up the temporary script\n",
    "        if script_path.exists():\n",
    "            script_path.unlink()\n",
    "        \n",
    "        return True\n",
    "        \n",
    "    except subprocess.CalledProcessError as e:\n",
    "        logger.error(f\"Failed to run {notebook_path.name}: {e}\")\n",
    "        return False\n",
    "\n",
    "\n",
    "def run_pipeline():\n",
    "    \"\"\"Run the complete ETL pipeline\"\"\"\n",
    "    logger.info(\"=\" * 70)\n",
    "    logger.info(\"FMCG INVENTORY ETL PIPELINE - REPRODUCIBLE RUN\")\n",
    "    logger.info(\"=\" * 70)\n",
    "    logger.info(f\"Start time: {datetime.datetime.now()}\")\n",
    "    logger.info(f\"Project root: {PROJECT_ROOT}\")\n",
    "    logger.info(\"=\" * 70)\n",
    "    \n",
    "    # Step 1: Check environment\n",
    "    logger.info(\"\\n[STEP 1] Checking environment...\")\n",
    "    if not check_python_version():\n",
    "        return False\n",
    "    if not check_requirements():\n",
    "        logger.warning(\"Some requirements may be missing. Continuing...\")\n",
    "    \n",
    "    # Step 2: Check input files\n",
    "    logger.info(\"\\n[STEP 2] Checking input files...\")\n",
    "    if not check_raw_files():\n",
    "        return False\n",
    "    if not check_notebooks():\n",
    "        return False\n",
    "    \n",
    "    # Step 3: Run the main notebook\n",
    "    logger.info(\"\\n[STEP 3] Running main pipeline...\")\n",
    "    \n",
    "    main_notebook = PROJECT_ROOT / 'main.ipynb'\n",
    "    if not main_notebook.exists():\n",
    "        logger.error(f\"main.ipynb not found at {main_notebook}\")\n",
    "        return False\n",
    "    \n",
    "    # Convert and run main.ipynb\n",
    "    try:\n",
    "        # Convert to script\n",
    "        script_path = main_notebook.with_suffix('.py')\n",
    "        cmd = [\n",
    "            'jupyter', 'nbconvert',\n",
    "            '--to', 'script',\n",
    "            '--output', 'main',\n",
    "            str(main_notebook)\n",
    "        ]\n",
    "        subprocess.check_call(cmd, cwd=main_notebook.parent)\n",
    "        \n",
    "        # Run the script\n",
    "        cmd = [sys.executable, str(script_path)]\n",
    "        result = subprocess.check_call(cmd, cwd=main_notebook.parent)\n",
    "        \n",
    "        # Clean up\n",
    "        if script_path.exists():\n",
    "            script_path.unlink()\n",
    "        \n",
    "        # Check if output files were created\n",
    "        output_files = [\n",
    "            DATA_PROCESSED / 'sales_cleaned.csv',\n",
    "            DATA_PROCESSED / 'orders_cleaned.csv',\n",
    "            DATA_PROCESSED / 'inventory_cleaned.csv',\n",
    "            DATA_PROCESSED / 'warehouses_cleaned.csv'\n",
    "        ]\n",
    "        \n",
    "        all_created = all(f.exists() for f in output_files)\n",
    "        \n",
    "        if all_created:\n",
    "            logger.info(\"\\n✅ Pipeline executed successfully!\")\n",
    "        else:\n",
    "            logger.warning(\"\\n⚠️  Some output files may be missing\")\n",
    "        \n",
    "        return all_created\n",
    "        \n",
    "    except subprocess.CalledProcessError as e:\n",
    "        logger.error(f\"Failed to run main.ipynb: {e}\")\n",
    "        return False\n",
    "\n",
    "\n",
    "# ============================================\n",
    "# 4. VERIFY REPRODUCIBILITY\n",
    "# ============================================\n",
    "\n",
    "def verify_reproducibility():\n",
    "    \"\"\"Verify all components needed for reproducibility\"\"\"\n",
    "    logger.info(\"\\n\" + \"=\" * 70)\n",
    "    logger.info(\"VERIFYING REPRODUCIBILITY (Q7)\")\n",
    "    logger.info(\"=\" * 70)\n",
    "    \n",
    "    checks = []\n",
    "    \n",
    "    # Check for README\n",
    "    readme_exists = (PROJECT_ROOT / 'README.md').exists()\n",
    "    checks.append(('README.md', readme_exists))\n",
    "    logger.info(f\"  {'✅' if readme_exists else '❌'} README.md\")\n",
    "    \n",
    "    # Check for requirements.txt\n",
    "    req_exists = (PROJECT_ROOT / 'requirements.txt').exists()\n",
    "    checks.append(('requirements.txt', req_exists))\n",
    "    logger.info(f\"  {'✅' if req_exists else '❌'} requirements.txt\")\n",
    "    \n",
    "    # Check for run_pipeline.py\n",
    "    run_exists = (PROJECT_ROOT / 'run_pipeline.py').exists()\n",
    "    checks.append(('run_pipeline.py', run_exists))\n",
    "    logger.info(f\"  {'✅' if run_exists else '❌'} run_pipeline.py\")\n",
    "    \n",
    "    # Check for source notebooks\n",
    "    src_dir = PROJECT_ROOT / 'src'\n",
    "    notebooks = ['extract.ipynb', 'transform.ipynb', 'validate.ipynb', \n",
    "                 'integrate.ipynb', 'analytics.ipynb']\n",
    "    for nb in notebooks:\n",
    "        exists = (src_dir / nb).exists()\n",
    "        checks.append((nb, exists))\n",
    "        logger.info(f\"  {'✅' if exists else '❌'} {nb}\")\n",
    "    \n",
    "    # Check for main.ipynb\n",
    "    main_exists = (PROJECT_ROOT / 'main.ipynb').exists()\n",
    "    checks.append(('main.ipynb', main_exists))\n",
    "    logger.info(f\"  {'✅' if main_exists else '❌'} main.ipynb\")\n",
    "    \n",
    "    # Check for data directories\n",
    "    raw_exists = DATA_RAW.exists()\n",
    "    checks.append(('data/raw/', raw_exists))\n",
    "    logger.info(f\"  {'✅' if raw_exists else '❌'} data/raw/\")\n",
    "    \n",
    "    processed_exists = DATA_PROCESSED.exists()\n",
    "    checks.append(('data/processed/', processed_exists))\n",
    "    logger.info(f\"  {'✅' if processed_exists else '❌'} data/processed/\")\n",
    "    \n",
    "    # Summary\n",
    "    all_passed = all(status for _, status in checks)\n",
    "    \n",
    "    logger.info(\"\\n\" + \"-\" * 70)\n",
    "    if all_passed:\n",
    "        logger.info(\"✅ ALL REPRODUCIBILITY CHECKS PASSED!\")\n",
    "        logger.info(\"   The pipeline is ready for reproduction.\")\n",
    "    else:\n",
    "        missing = [name for name, status in checks if not status]\n",
    "        logger.warning(f\"⚠️  Missing {len(missing)} items:\")\n",
    "        for item in missing:\n",
    "            logger.warning(f\"   - {item}\")\n",
    "    \n",
    "    return all_passed\n",
    "\n",
    "\n",
    "# ============================================\n",
    "# 5. MAIN EXECUTION\n",
    "# ============================================\n",
    "\n",
    "def main():\n",
    "    \"\"\"Main execution function\"\"\"\n",
    "    print(\"\\n\" + \"=\" * 70)\n",
    "    print(\"FMCG INVENTORY ETL PIPELINE\")\n",
    "    print(\"Reproducible Pipeline Runner\")\n",
    "    print(\"=\" * 70)\n",
    "    \n",
    "    # Step 1: Check environment\n",
    "    logger.info(\"\\n[1/5] Checking environment...\")\n",
    "    if not check_python_version():\n",
    "        sys.exit(1)\n",
    "    \n",
    "    # Step 2: Check requirements\n",
    "    logger.info(\"\\n[2/5] Checking requirements...\")\n",
    "    if not check_requirements():\n",
    "        logger.warning(\"Some requirements may be missing. Please install: pip install -r requirements.txt\")\n",
    "    \n",
    "    # Step 3: Check input files\n",
    "    logger.info(\"\\n[3/5] Checking input files...\")\n",
    "    if not check_raw_files():\n",
    "        logger.error(\"Please place raw CSV files in data/raw/\")\n",
    "        sys.exit(1)\n",
    "    \n",
    "    # Step 4: Verify reproducibility\n",
    "    logger.info(\"\\n[4/5] Verifying reproducibility (Q7)...\")\n",
    "    verify_reproducibility()\n",
    "    \n",
    "    # Step 5: Run the pipeline\n",
    "    logger.info(\"\\n[5/5] Running the ETL pipeline...\")\n",
    "    success = run_pipeline()\n",
    "    \n",
    "    # Final summary\n",
    "    logger.info(\"\\n\" + \"=\" * 70)\n",
    "    if success:\n",
    "        logger.info(\"✅ PIPELINE COMPLETED SUCCESSFULLY!\")\n",
    "        logger.info(\"   The pipeline is reproducible and ready for review.\")\n",
    "        logger.info(f\"   Check logs: {LOGS_DIR / 'pipeline_execution.log'}\")\n",
    "        logger.info(f\"   Check output: {DATA_PROCESSED}\")\n",
    "    else:\n",
    "        logger.error(\"❌ PIPELINE FAILED!\")\n",
    "        logger.error(\"   Please check the logs for errors.\")\n",
    "    \n",
    "    logger.info(\"=\" * 70)\n",
    "    \n",
    "    return 0 if success else 1\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    sys.exit(main())"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.14.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
